Fixing top bar
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #125
Opened 2023-11-22 08:37 UTC by christian140398

Closes #{ISSUE_ID}

### Changes/Additions:

- Fixed checkbox

2023-11-23 14:12 UTC, DenFlyvendeGed approved these changes
LGTM

2023-11-24 08:32 UTC, TSKsmiley commented on src/lib/components/topBar/TopBar.svelte
> +					window.open("https://www.ecdar.net/");
this does not seem to work in tauri (have only tested on mac)

2023-11-29 08:53 UTC, atjn requested changes

2023-11-29 08:53 UTC, atjn commented on package.json
> +		"yarn": "^1.22.21",
This is telling yarn to bundle the yarn source code with the web app.

2023-11-29 08:53 UTC, atjn commented on src/lib/components/topBar/TopBar.svelte
> +			<div style="position: absolute; left: 2%;">
Please use the standardized modal that is being merged here: https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/pull/111/files#diff-4fa9b2f0e22c217008f008d25d07f473d343030aca709b90d8ab2bfb57d24770

Any popup should use this modal to ensure consistency in the UI.

2023-12-14 16:50 UTC, KamyaPA approved these changes
LGTM

2023-12-14 19:18 UTC, atjn approved these changes
LGTM

2023-12-14 19:24 UTC, merged