Load save
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #42
Opened 2023-10-04 13:07 UTC by KamyaPA

Closes #31

### Changes/Additions:
- Added class Project
- Load, Save, QuickSave is created for Tauri
- Load is created for the Browser (Save is setup but not implemented)
- Renamed query.ts -to-> Query.ts

2023-10-06 13:04 UTC, BaBrixx requested changes
I am not done reviewing and will continue next week. I've so far found a small mistake regarding naming. In addition to the locations where I've proposed changes the following file and any other file using the specific enum should be changed:

[](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/blob/main/src/lib/classes/automaton/DeclarationType.ts)

2023-10-12 11:00 UTC, atjn commented
I will fix errors

2023-10-13 11:47 UTC, BaBrixx requested changes
Probably shouldn't downgrade this package

2023-10-13 11:47 UTC, BaBrixx commented on yarn.lock
> +svelte-google-materialdesign-icons@^0.8.1:
```suggestion
svelte-google-materialdesign-icons@^0.8.2:
```

2023-10-16 11:07 UTC, BaBrixx approved these changes
LGTM! Nice work!😍
![give-me-your-money-gamer-nexus](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90306530/6c752e8d-d245-44b5-a1fb-82f5ddc5a285)
![thanks-steve-intel](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90306530/cdd5cf74-9b6d-49c5-a2e3-419e516ab840)

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/automaton/OperatorType.ts
> + * The values are lover case because of compatibility
```suggestion
 * The values are lower case because of compatibility
```

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/automaton/System.ts
>  					// BECAUSE OF COMPATIBILITY
```suggestion

```

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/automaton/System.ts
>  					/// BECAUSE OF COMPATIBILITY
```suggestion

```

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/automaton/raw/RawQuery.ts
> + * The used for Zod
jeg ved ikke hvad det skal betyde

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/project/Project.ts
> +	 * List of optional features this project
```suggestion
	 * List of optional features in the project
```

2023-10-16 12:59 UTC, DenFlyvendeGed commented on src/lib/classes/project/adapters/TauriProject.ts
> +					`There already exists a directory named ${this.name} in that directory, would you like to over write`,
```suggestion
					`There already exists a directory named ${this.name} in that directory, would you like to overwrite`,
```

2023-10-16 13:24 UTC, KamyaPA commented on src/lib/classes/automaton/raw/RawQuery.ts
> + * The used for Zod
Skulle gerne have ændret dette

2023-10-16 13:37 UTC, DenFlyvendeGed approved these changes

2023-10-16 13:43 UTC, BaBrixx approved these changes
LEBTM🤩

(Looks even better to me)

2023-10-16 13:44 UTC, merged