Console
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #45
Opened 2023-10-06 11:30 UTC by tr0ub1eM4k3r

Closes #{35}

### Changes/Additions:
- Added basic console functionality, with a collapsible state, different tabs and posting strings to the different tabs
-

2023-10-06 12:12 UTC, NybyDK commented
![image](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/45389841/425399aa-98f7-4596-a81f-7f61dcbdad79)
Are we doing it wrong or can we not see the bottom ones? Sending the text "Nederst" 5 times but we can't see all of them

https://i.gyazo.com/4e392be4c3c098456aa613483f811ce7.gif
Weird behavior when the window is resized

When selecting the text to copy it, should we get rid of the ">"s, i.e., the arrows should be non-selectable?

When clicking the up arrow, it pushes the rest of the page up, but maybe it should layer on top instead, and not push anything?

2023-10-06 12:16 UTC, BaBrixx commented
The bug with not all of the elements showing up in the Console and being able to scroll "below" the bottom of the screen was fixed by removing all of the buttons in the footer so maybe you are calculating the height of the console wrong?

2023-10-06 12:23 UTC, NybyDK commented
Can we have the frontend/backend buttons show which one is currently used, that is, if I am viewing backend errors, the backend button could have a different color or underline or something

2023-10-06 12:29 UTC, BaBrixx requested changes

2023-10-06 12:29 UTC, BaBrixx commented on src/lib/components/console/Console.svelte
> +	}
Maybe this enum should be in its own file so that it can be used by other components?

2023-10-06 12:33 UTC, NybyDK commented
In the old GUI, the console can be resized by dragging it at the top to get any size, we should do this too

2023-10-06 12:50 UTC, NybyDK requested changes

2023-10-06 12:50 UTC, NybyDK commented on src/lib/components/console/ConsoleLine.svelte
> +	</nobr>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr
> Deprecated (...) it was never standard HTML, so you shouldn't use it. Instead, use the CSS property [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)

2023-10-06 13:00 UTC, NybyDK commented
For super long errors, it's currently scrolling on the x axis, perhaps it should wrap to the next line but still be under the same ">" arrow, something like

> error here
> another error
> this error is super long and yeehoo wooooooooooooooooo
and it continues on this line
> error :(

2023-10-13 12:22 UTC, BaBrixx requested changes
When adding a large amount of elements inside the sidebars, the site reverts to be scrollable and the console is gone.
![ezgif-1-41292c2081](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90306530/3d76e5a0-0f10-4e84-87d4-370cbc1c6e75)

2023-10-19 06:50 UTC, NybyDK approved these changes
LOOKS GOOD TO ME

2023-10-19 08:04 UTC, BaBrixx approved these changes
LGTM

2023-10-19 13:07 UTC, KamyaPA approved these changes
CSS classes still in camelCase but approving because of control flow

2023-10-19 13:07 UTC, merged