Create style guide
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #52
Opened 2023-10-19 09:43 UTC by atjn

2023-11-10 12:45 UTC, Jesper276 requested changes
LAGTM remember oxford comma

2023-11-10 12:45 UTC, Jesper276 commented on .github/CONTRIBUTING.md
> +For information about file, class, interface and variable naming conventions, code practices, project file structure and rules about the usage of TS types, read the [styleguide](../styleguide.md) fil
```suggestion
For information about file, class, interface and variable naming conventions, code practices, project file structure, and rules about the usage of TS types, read the [styleguide](../styleguide.md) file.
```

2023-11-10 12:46 UTC, Jesper276 submitted a review, later dismissed
LGTM

2023-11-13 14:15 UTC, Jesper276 approved these changes
LGTM
![GIF](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90216888/ef847008-1e49-4718-ba71-8d0c9c5e1e07)

2023-11-14 09:15 UTC, DenFlyvendeGed approved these changes
LGTM

2023-11-15 07:11 UTC, merged