44-2-top-bar-group5
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #55
Opened 2023-10-19 13:47 UTC by christian140398

Closes #44 #2 

### Changes/Additions:

- Added Topbar
- Added All navigations
- Missing functionality for buttons, Open project is implemented as example, but does nothing yet

2023-10-20 11:03 UTC, KamyaPA submitted a review, later dismissed
LGTM

2023-10-20 11:12 UTC, NybyDK requested changes
besides this i am ready to approve

2023-10-20 11:12 UTC, NybyDK commented on yarn.lock
> +svelte-google-materialdesign-icons@^0.8.1:
no downgrade pls :(

2023-10-20 11:12 UTC, NybyDK commented on src/lib/components/topBar/TopBar.svelte
> +			}}
```suggestion
			name="Scaling"
			on:click={() => {
				console.log("Scaling");
			}}
```

2023-10-20 11:45 UTC, Jesper276 requested changes
![image](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90216888/0c45ae7a-2496-441d-93b4-1e8af60bd8c8)

can you add icons?

2023-10-20 11:46 UTC, Jesper276 requested changes
![image](https://github.com/ECDAR-AAU-SW-P5/Ecdar-GUI-Web/assets/90216888/1092d68f-928d-4c02-b513-87621e589168)
can the submenu functionality also be added?!?

2023-10-23 15:34 UTC, NybyDK submitted a review, later dismissed

2023-10-25 10:47 UTC, NybyDK commented on src/lib/components/topBar/TopBar.svelte
> +	import * as Icon from "svelte-google-materialdesign-icons";
according to our svelte expert, this is not good for the bundling, instead, we should only import the ones we use

2023-10-25 10:47 UTC, NybyDK commented on src/lib/components/topBar/TopBar.svelte
> +	import * as Icon from "svelte-google-materialdesign-icons";
i only meant to highlight line 5 xd

2023-11-07 09:23 UTC, Jesper276 approved these changes
Lgtm

2023-11-08 12:04 UTC, KamyaPA approved these changes
LGTM

2023-11-08 12:04 UTC, merged