Loading queries example
ECDAR-AAU-SW-P5/Ecdar-GUI-Web pull request #91
Opened 2023-10-27 11:50 UTC by NybyDK

Closes #73 according to Jesper

### Changes/Additions:
- added testings for queries
- connected frontend query to backend structure stuff

2023-11-10 11:05 UTC, DenFlyvendeGed approved these changes
LGTM

2023-11-10 12:01 UTC, NybyDK commented
Jeg vil da forhelvede ikke dismiss, jeg vil bare have main ind for 4. gang 😭

2023-11-10 13:17 UTC, BaBrixx requested changes

2023-11-10 13:17 UTC, BaBrixx commented on src/lib/components/query/Query.svelte
> +
I cred🥲

2023-11-10 13:17 UTC, BaBrixx commented on src/lib/components/query/QueryDropDownMenu.svelte
The context menu should disappear when it is already open and one clicks the button again.

2023-11-10 13:18 UTC, Jesper276 commented on src/lib/components/query/Query.svelte
> +
i kill

2023-11-10 13:33 UTC, NybyDK commented on src/lib/components/query/QueryDropDownMenu.svelte
Will be added to ContextMenu itself, will create an issue

2023-11-10 13:34 UTC, BaBrixx approved these changes
LGTM

2023-11-13 12:19 UTC, DenFlyvendeGed approved these changes
LGTM

2023-11-13 12:19 UTC, merged